### ISSUE TITLE
7B Fine-tuning GPU requirements

### ISSUE THREAD

**Issue by ArslanTu** [facebookresearch/llama-recipes#100]
I have 8 * RTX 3090 (24 G), but still encountered with "CUDA out of memory" when training 7B model (enable fsdp with bf16 and without peft). 
I'm  sure the OOM happened in `model = FSDP(model, ...)` according to the log.
I'm wondering the minimum GPU requirements for 7B model using FSDP Only (full_shard, parameter parallelism).

**Comment by HamidShojanazeri** [comment]
@ArslanTu For 7B with FSDP only without PEFT, on 4 A100 40 GB, Max CUDA memory reserved was 29 GB and if you use this [PR](https://github.com/facebookresearch/llama-recipes/pull/97), on A100 that make use of flash attention it reduced the max reserved to 27.  Can you pls share your command/ error logs.

**Comment by huangwei2913** [comment]
I used the https://brev.dev/blog/fine-tuning-llama-2 to test the fine-tune GPU memory requirement.  I have only one RTX 3090 card, and installed the drivers and toolkit as shown in the following:
(base) huangwei@huangwei-MS-7D42:~$ nvidia-smi
Thu Aug 17 16:55:13 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   53C    P8    29W / 350W |  23643MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       970      G   /usr/lib/xorg/Xorg                 98MiB |
|    0   N/A  N/A      1287      G   /usr/bin/gnome-shell               28MiB |
|    0   N/A  N/A     20678      C   ...da3/envs/llama/bin/python     7804MiB |
|    0   N/A  N/A    108900      G   /usr/lib/firefox/firefox          152MiB |
|    0   N/A  N/A    170370      C   ...envs/tunellama/bin/python    15556MiB |
+-----------------------------------------------------------------------------+

**My logs are as follows:

OutOfMemoryError                          Traceback (most recent call last)
Cell In[6], line 31
     22 trainer = Trainer(
     23     model=model,
     24     args=training_args,
   (...)
     27     callbacks=[profiler_callback] if enable_profiler else [],
     28 )
     30 # Start training
---> 31 trainer.train()

File ~/anaconda3/envs/tunellama/lib/python3.8/site-packages/transformers/trainer.py:1539, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1534     self.model_wrapped = self.model
   1536 inner_training_loop = find_executable_batch_size(
   1537     self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size
   1538 )
-> 1539 return inner_training_loop(
   1540     args=args,
   1541     resume_from_checkpoint=resume_from_checkpoint,
   1542     trial=trial,
   1543     ignore_keys_for_eval=ignore_keys_for_eval,
   1544 )

File ~/anaconda3/envs/tunellama/lib/python3.8/site-packages/transformers/trainer.py:1809, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1806     self.control = self.callback_handler.on_step_begin(args, self.state, self.control)
   1808 with self.accelerator.accumulate(model):
-> 1809     tr_loss_step = self.training_step(model, inputs)
   1811 if (
   1812     args.logging_nan_inf_filter
   1813     and not is_torch_tpu_available()
   1814     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
   1815 ):
   1816     # if loss is nan or inf simply add the average of previous logged losses
   1817     tr_loss += tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)

File ~/anaconda3/envs/tunellama/lib/python3.8/site-packages/transformers/trainer.py:2665, in Trainer.training_step(self, model, inputs)
   2663         scaled_loss.backward()
   2664 else:
-> 2665     self.accelerator.backward(loss)
   2667 return loss.detach() / self.args.gradient_accumulation_steps

File ~/anaconda3/envs/tunellama/lib/python3.8/site-packages/accelerate/accelerator.py:1853, in Accelerator.backward(self, loss, **kwargs)
   1851     self.scaler.scale(loss).backward(**kwargs)
   1852 else:
-> 1853     loss.backward(**kwargs)

File ~/anaconda3/envs/tunellama/lib/python3.8/site-packages/torch/_tensor.py:487, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    477 if has_torch_function_unary(self):
    478     return handle_torch_function(
    479         Tensor.backward,
    480         (self,),
   (...)
    485         inputs=inputs,
    486     )
--> 487 torch.autograd.backward(
    488     self, gradient, retain_graph, create_graph, inputs=inputs
    489 )

File ~/anaconda3/envs/tunellama/lib/python3.8/site-packages/torch/autograd/__init__.py:200, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    195     retain_graph = create_graph
    197 # The reason we repeat same the comment below is that
    198 # some Python versions print out the first line of a multi-line function
    199 # calls in the traceback and some print out the last line
--> 200 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202     allow_unreachable=True, accumulate_grad=True)

File ~/anaconda3/envs/tunellama/lib/python3.8/site-packages/torch/autograd/function.py:274, in BackwardCFunction.apply(self, *args)
    270     raise RuntimeError("Implementing both 'backward' and 'vjp' for a custom "
    271                        "Function is not allowed. You should only implement one "
    272                        "of them.")
    273 user_fn = vjp_fn if vjp_fn is not Function.vjp else backward_fn
--> 274 return user_fn(self, *args)

File ~/anaconda3/envs/tunellama/lib/python3.8/site-packages/torch/utils/checkpoint.py:157, in CheckpointFunction.backward(ctx, *args)
    153 if len(outputs_with_grad) == 0:
    154     raise RuntimeError(
    155         "none of output has requires_grad=True,"
    156         " this checkpoint() is not necessary")
--> 157 torch.autograd.backward(outputs_with_grad, args_with_grad)
    158 grads = tuple(inp.grad if isinstance(inp, torch.Tensor) else None
    159               for inp in detached_inputs)
    161 return (None, None) + grads

File ~/anaconda3/envs/tunellama/lib/python3.8/site-packages/torch/autograd/__init__.py:200, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    195     retain_graph = create_graph
    197 # The reason we repeat same the comment below is that
    198 # some Python versions print out the first line of a multi-line function
    199 # calls in the traceback and some print out the last line
--> 200 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202     allow_unreachable=True, accumulate_grad=True)

OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 23.69 GiB total capacity; 12.27 GiB already allocated; 620.19 MiB free; 14.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

By the way,  i used the pytorch 2.0.1, and transformers 0.39.1, training on dataset https://huggingface.co/datasets/samsum/tree/main/data.  My question is how to aviod the outofmemoryerror

**Comment by huangwei2913** [comment]
I finally found https://iamholumeedey007.medium.com/memory-management-using-pytorch-cuda-alloc-conf-dabe7adec130 solve my question, by adding the following configuration 

import os
# Set PYTORCH_CUDA_ALLOC_CONF environment variable
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "caching_allocator

 It's OK to tune llama on nvidia rtx 3090. I don't understand FSDP  yet.

**Comment by yuweikun** [comment]
>i also use 3090*8 
it still not work

**Comment by huangwei2913** [comment]
More information is necessary, please show some logs

yuweikun ***@***.***> 于2023年8月18日周五 20:25写道：

**Comment by Antinis** [comment]
> I finally found https://iamholumeedey007.medium.com/memory-management-using-pytorch-cuda-alloc-conf-dabe7adec130 solve my question, by adding the following configuration
> 
> import os
> 
> # Set PYTORCH_CUDA_ALLOC_CONF environment variable
> os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "caching_allocator
> 
> It's OK to tune llama on nvidia rtx 3090. I don't understand FSDP yet.

Hi, I got an error when allocating os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "caching_allocator", here's the log:

`Traceback (most recent call last):
  File "multimodel_training.py", line 203, in <module>
    run()
  File "multimodel_training.py", line 198, in run
    train()
  File "multimodel_training.py", line 146, in train
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 404, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: caching_allocator
[10300] Initializing process group with: {'MASTER_ADDR': '10.0.12.103', 'MASTER_PORT': '11451', 'WORLD_SIZE': '8', 'LOCAL_WORLD_SIZE': '8'}
Traceback (most recent call last):
  File "multimodel_training.py", line 203, in <module>
    run()
  File "multimodel_training.py", line 198, in run
    train()
  File "multimodel_training.py", line 146, in train
    torch.cuda.set_device(local_rank)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 404, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: caching_allocator`

My torch version is 2.1. How could it be solved?
By the way, I am also wondering after you allocating the caching_allocator, do you continue to use FSDP? Thank you!
