### ISSUE TITLE
Incorrect loss computation for alpaca dataset

### ISSUE THREAD

**Issue by wuyifan18** [facebookresearch/llama-recipes#101]
According to the LLAMA2 paper, the loss is only computed for the answer tokens. The default ignore_index of CrossEntropyLoss used in LLAMA2 is -100, which uses to specify a target value that is ignored and does not contribute to the input gradient.
So, if we want to ignore some tokens without gradient contribution, we should set the label of these tokens to -100.

However, I found that the labels of the prompt are set to 0 as follows:
https://github.com/facebookresearch/llama-recipes/blob/597e63429ca79abf605bbc2066642e7a99b053c6/ft_datasets/alpaca_dataset.py#L64-L69

Is there something wrong?

**Comment by HamidShojanazeri** [comment]
@wuyifan18 thanks for opening this issue, would be interested to send a PR ? I wold be happy to review and help getting it merged.

**Comment by HamidShojanazeri** [comment]
addressed in this[ PR](https://github.com/facebookresearch/llama-recipes/pull/107).

**Comment by cy565025164** [comment]
Key: avg_train_prep, Value: nan
Key: avg_train_loss, Value: nan
Key: avg_eval_prep, Value: nan
Key: avg_eval_loss, Value: inf
