### ISSUE TITLE
Prompts for finetuning Llama v2 7B/13B

### ISSUE THREAD

**Issue by shubhamagarwal92** [facebookresearch/llama-recipes#114]
### 🚀 The feature, motivation and pitch

Hi! 

I am following the tutorial here: https://github.com/facebookresearch/llama-recipes/blob/main/quickstart.ipynb

In code block [4], we have
```
eval_prompt = "Some sentence"
model_input = tokenizer(eval_prompt, return_tensors="pt").to("cuda")

model.eval()
with torch.no_grad():
    print(tokenizer.decode(model.generate(**model_input, max_new_tokens=100)[0], skip_special_tokens=True))

```
where `eval prompt` is a natural language text. 

Shouldn't we follow the prompt template as mentioned [here](https://github.com/facebookresearch/llama/blob/main/llama/generation.py#L247)? Is this prompt template specifically for chat agents like 7B-chat, 13B-chat, 70B-chat? Or do we also need them for 7B, 13B and 70B models? 

### Alternatives

```
<s>[INST] <<SYS>>
{{ system_prompt }}
<</SYS>>

{{ user_message }} [/INST]
```

https://github.com/huggingface/blog/blob/main/llama2.md#how-to-prompt-llama-2

**Comment by HamidShojanazeri** [comment]
@shubhamagarwal92 thanks for pointing it out, it depends if you are using the chat model or base model. The special tokens you mentioned above are for the chat models. We also welcome contributions very much, if you like to add a chat model fine-tuning example, happy to help review and merge.

**Comment by shubhamagarwal92** [comment]
Thanks @HamidShojanazeri for the response! I will raise a PR for the chat fine-tuning example soon. :)

**Comment by liebkne** [comment]
[**@HamidShojanazeri**](https://github.com/HamidShojanazeri) commented on [Aug 12, 2023, 2:45 AM GMT+8](https://github.com/facebookresearch/llama-recipes/issues/114#issuecomment-1675217362 "2023-08-11T18:45:13Z - Replied by Github Reply Comments"):
> [@shubhamagarwal92](https://github.com/shubhamagarwal92) thanks for pointing it out, it depends if you are using the chat model or base model. The special tokens you mentioned above are for the chat models. We also welcome contributions very much, if you like to add a chat model fine-tuning example, happy to help review and merge.

Hi, does this mean `llm_finetuning.py` is not for fine-tuning `7B/13B/70B-chat` models? I didn't find something related mentioned in https://github.com/facebookresearch/llama-recipes/blob/main/docs/LLM_finetuning.md .

**Comment by timothylimyl** [comment]
@liebkne , if you want to finetune for any other task that has a prompt template format, you will need to set up so that your input prompt gets transformed accordingly.

**Comment by HamidShojanazeri** [comment]
> [**@HamidShojanazeri**](https://github.com/HamidShojanazeri) commented on [Aug 12, 2023, 2:45 AM GMT+8](https://github.com/facebookresearch/llama-recipes/issues/114#issuecomment-1675217362):
> 
> > [@shubhamagarwal92](https://github.com/shubhamagarwal92) thanks for pointing it out, it depends if you are using the chat model or base model. The special tokens you mentioned above are for the chat models. We also welcome contributions very much, if you like to add a chat model fine-tuning example, happy to help review and merge.
> 
> Hi, does this mean `llm_finetuning.py` is not for fine-tuning `7B/13B/70B-chat` models but only for `7B/13B/70B` models? I didn't find something related mentioned in https://github.com/facebookresearch/llama-recipes#fine-tuning and https://github.com/facebookresearch/llama-recipes/blob/main/docs/LLM_finetuning.md .

the code here is agnostic to that so, it depends on your task it can support both.
