### ISSUE TITLE
training.mixed_precision=True, training.use_fp16=False, fsdp.pure_bf16=False

### ISSUE THREAD

**Issue by ToddMorrill** [facebookresearch/llama-recipes#119]
### System Info

Collecting environment information...
PyTorch version: 2.1.0.dev20230815+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        4
CPU max MHz:                     4500.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        7200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_pkg_req md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        8 MiB (8 instances)
L3 cache:                        11 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] torch==2.1.0.dev20230815+cu121
[pip3] torchaudio==2.1.0.dev20230815+cu121
[pip3] torchvision==0.16.0.dev20230815+cu121
[pip3] triton==2.0.0
[conda] No relevant packages

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### 🐛 Describe the bug

What is the expected behavior of this mode with respect to parameter data types and their impact on memory and throughput?
```
training.mixed_precision=True, training.use_fp16=False, fsdp.pure_bf16=False
```
I see that this triggers the `bfSixteen` `mixed_precision.py` policy but in practice, this mode appears to perform the same as `fp32` with respect to memory usage and throughput as measured by TFLOPS and tokens/second. Meanwhile, `training.mixed_precision=True, training.use_fp16=True, fsdp.pure_bf16=False` shows strong improvements with respect to memory and throughput relative to both
1. `training.mixed_precision=True, training.use_fp16=False, fsdp.pure_bf16=False` (i.e. this should be `bf16`) and
2. `training.mixed_precision=False, training.use_fp16=False, fsdp.pure_bf16=False` (i.e. this should be `fp32`).

Finally, it is only when I run `training.mixed_precision=True, training.use_fp16=False, fsdp.pure_bf16=True` that I see the memory and throughput improvements for `bf16`. 

I should mention that I added GPT-2 support throughout the entire llama-recipes repo for rapid iteration and debugging before I scale up but I don't think that should impact the issue I'm describing above.

### Error logs

There are no errors.

### Expected behavior

I'm hoping to get some clarity on the expected behavior. My understanding of mixed precision training is that you retain a master copy of the weights in `fp32` and perform forward/backward passes in the lower precision data format (e.g. `fp16` or `bf16`) by casting the weights to these data types on each iteration. This should be governed by the mixed precision policy. I don't know how this differs in the fsdp.pure_bf16=True scenario.

**Comment by HamidShojanazeri** [comment]
@ToddMorrill closing this as been fixed in the above PR.
