### ISSUE TITLE
Pretrain using fairscale with model parallelism?

### ISSUE THREAD

**Issue by glin93** [facebookresearch/llama-recipes#13]
Currently, all snippets are based on Hugging Face Transformers. Will there be examples of how to fine-tune full parameters using FairScale? It seems that the model was originally pre-trained using FairScale and model parallelism. Such examples would be useful for fine-tuning or continuing to train the model.

**Comment by HamidShojanazeri** [comment]
@glin93 we are mostly investing on PyTorch FSDP for training in this repo for now. You might be able to open an issue on the [llama](https://github.com/facebookresearch/llama) if interested in FairScale finetuning recipes.
