### ISSUE TITLE
why i can not load model from llama-2-7b,

### ISSUE THREAD

**Issue by QJShan** [facebookresearch/llama-recipes#14]
![image](https://github.com/facebookresearch/llama-recipes/assets/131762142/28ddfedd-9a5a-4e72-b17a-9338f55c8bce)
the error are as follows:
![image](https://github.com/facebookresearch/llama-recipes/assets/131762142/74df0647-1943-4b69-83c6-14c6a5696bd7)

**Comment by QJShan** [comment]
> conver

sorry,i do not know how to conver from pth to bin,can you help me. think you.
the file with postfix pth is obtained from download.sh in llama repo.

**Comment by chauhang** [comment]
@QJShan Can you please try giving full absolute path for the local model copy?

**Comment by byeongcheoljo** [comment]
@QJShan 


## Install HuggingFace Transformers from source
pip install git+https://github.com/huggingface/transformers
cd transformers

python src/transformers/models/llama/convert_llama_weights_to_hf.py \
    --input_dir /path/to/downloaded/llama/weights --model_size 7B --output_dir models_hf/7B

**Comment by QJShan** [comment]
> Can you please try giving full absolute path for the local model copy?

I have tried using absolute paths as follows:
![image](https://github.com/facebookresearch/llama-recipes/assets/131762142/e5dc2ace-f8eb-4e2c-8e15-160c17c7dd44)
the error is same with above

**Comment by HamidShojanazeri** [comment]
@QJShan wondering if it would be easier to pick up models from HF, you can checkout this link https://huggingface.co/meta-llama/Llama-2-7b first apply through "Meta" form then request access for HF on the same link. Its fairly quick. This way you dont have to think of conversion.

**Comment by williamqzy** [comment]
try to revise the folder name of "llama-2-7b" to "7B"?

**Comment by HamidShojanazeri** [comment]
@QJShan this seems to be solved as converted weights are already available on the hub, https://huggingface.co/meta-llama

**Comment by rmngllnn** [comment]
@HamidShojanazeri I saw you can now use llama-2 directly with HF but there is no method to use the downloaded models on your local computer ? I couldn't see any response about this as I'd like to use local weights and not on the hubs (as I'd like my colleagues to also use easily these models)
