### ISSUE TITLE
How can I load data into multiple GPUs?

### ISSUE THREAD

**Issue by Lucien20000118** [facebookresearch/llama-recipes#168]
My hardware :
1. Two RTX3060, each 12 GB
2. RAM 32GB

Is it possible to run the model, on Windows or WSL?

**Comment by jspisak** [comment]
transferring this to the llama-recipes repo and tagging @jeffdaily from AMD for help here..

**Comment by Lucien20000118** [comment]
https://github.com/facebookresearch/llama/issues/665#issuecomment-1709317985 
It works in my case.
