### ISSUE TITLE
 llama2&recipes-map module library frame composition

### ISSUE THREAD

**Issue by ziwang-com** [facebookresearch/llama-recipes#17]
全球首发，llama2系列模块库架构图 Global launch, llama2-map module library frame composition
[https://github.com/ziwang-com/AGI-MAP](https://github.com/ziwang-com/AGI-MAP)

![llama2-recipes_inference_safety_utils](https://github.com/facebookresearch/llama-recipes/assets/11691791/dd5c9a14-c9a2-4a5b-b579-820b0d48d0de)

**Comment by HamidShojanazeri** [comment]
@ziwang-com thanks for the suggestion pls make a PR if you think that fits into our doc, will review there.
