### ISSUE TITLE
How to load 13B model in a single GPU?

### ISSUE THREAD

**Issue by corlder** [facebookresearch/llama-recipes#172]
Hi, I want to load 13B or larger model in a single A100 80G, but find that the two shards of the model are ought to be loaded in 2 GPUs, is there any way to consolidate the two shards into one file?

**Comment by Gooongna** [comment]
> > The 7B model works flawlessly, however the higher MP's are turning out to be an issue...
> 
> True. 13B MP is 2 and required 27GB VRAM. So it can run in a single A100 80GB or 40GB, but after modying the model.
> 
> Aside: if you don't know, Model Parallel (MP) encompasses both Pipeline Parallel (PP) and Tensor Parallel (TP). PP shards layers. TP shards each tensor. People always confuse them.
> 
> > After Fiddeling around a bit I think I came up with a solution, you can indeed try to run everything on a single GPU
> 
> The model by default is configured for distributed GPU (more than 1 GPU). A modified model (`model.py`) below should works with a single GPU. In addition, I also lowered the batch size to 1 so that the model can fit within VRAM.
> 
> ```python
> class ModelArgs:
>     dim: int = 512
>     n_layers: int = 8
>     n_heads: int = 8
>     vocab_size: int = -1
>     multiple_of: int = 256
>     norm_eps: float = 1e-5
> 
>     max_batch_size: int = 1 # <-- change this line from 32
> 
> # ...
> 
> class Attention(nn.Module):
>     def __init__(self, args: ModelArgs):
>         super().__init__()
> 
>         self.n_local_heads = args.n_heads // 1 # <-- change this. previous: args.n_heads // fs_init.get_model_parallel_world_size()
>         self.head_dim = args.dim // args.n_heads
> 
>         self.wq = nn.Linear( # <-- change line: previous: ColumnParallelLinear
>             args.dim,
>             args.n_heads * self.head_dim,
>             bias=False,
>             input_is_parallel=True, # <-- remove this line
>             init_method=lambda x: x, # <-- remove this line
>         )
>         self.wk = nn.Linear( # <-- change line: previous: ColumnParallelLinear
>             args.dim,
>             args.n_heads * self.head_dim,
>             bias=False,
>             input_is_parallel=True, # <-- remove this line
>             init_method=lambda x: x, # <-- remove this line
>         )
>         self.wv = nn.Linear( # <-- change line: previous: ColumnParallelLinear
>             args.dim,
>             args.n_heads * self.head_dim,
>             bias=False,
>             input_is_parallel=True, # <-- remove this line
>             init_method=lambda x: x, # <-- remove this line
>         )
>         self.wo = nn.Linear( # <-- change line: previous: RowParallelLinear
>             args.n_heads * self.head_dim,
>             args.dim,
>             bias=False,
>             input_is_parallel=True, # <-- remove this line
>             init_method=lambda x: x, # <-- remove this line
>         )
> 
> # ...
> 
> class FeedForward(nn.Module):
>     def __init__(
>         self,
>         dim: int,
>         hidden_dim: int,
>         multiple_of: int,
>     ):
>         super().__init__()
>         hidden_dim = int(2 * hidden_dim / 3)
>         hidden_dim = multiple_of * ((hidden_dim + multiple_of - 1) // multiple_of)
> 
>         self.w1 = nn.Linear( # <-- change this. previous: ColumnParallelLinear
>             dim, hidden_dim, bias=False, gather_output=False, init_method=lambda x: x
>         )
>         self.w2 = nn.Linear( # <-- change this. previous: RowParallelLinear
>             hidden_dim, dim, bias=False, input_is_parallel=True, init_method=lambda x: x
>         )
>         self.w3 = nn.Linear( # <-- change this. previous: ColumnParallelLinear
>             dim, hidden_dim, bias=False, gather_output=False, init_method=lambda x: x
>         )
> 
> # ...
> 
> class Transformer(nn.Module):
>     def __init__(self, params: ModelArgs):
>         super().__init__()
>         self.params = params
>         self.vocab_size = params.vocab_size
>         self.n_layers = params.n_layers
> 
>         self.tok_embeddings = nn.Embedding( # <-- change this. previous: ParallelEmbedding
>             params.vocab_size, params.dim
>         )
> 
>         self.layers = torch.nn.ModuleList()
>         for layer_id in range(params.n_layers):
>             self.layers.append(TransformerBlock(layer_id, params))
> 
>         self.norm = RMSNorm(params.dim, eps=params.norm_eps)
>         self.output = nn.Linear( # <-- change this. previous: ColumnParallelLinear
>             params.dim, params.vocab_size, bias=False
>         )
> 
> # ...
> ```
> 
> Modify those lines I mentioned in the code above. Basically, we removed all model parallel codes to make it work.
> 
> Edit 1: I forgot to include the `example.py` modifications, here you go in case you need it: https://github.com/cedrickchee/llama/blob/main/chattyllama/inference.py
> 
> Edit 2: No `torchrun` needed for this port. README says: "The provided `example.py` can be run on a single or multi-gpu node with `torchrun`"

I tried to modify model.py as suggested, but it still asserting error of 'AssertionError: Loading a checkpoint for MP=2 but world size is 1' no matter I use torchrun with 1 GPU or run it simply with 'python example.py'. Could you show your command line how did you run your exampl.py to load 13B model? Thanks!

**Comment by HamidShojanazeri** [comment]
closing this is more on original llama code stack, here focus is in HF checkpoints, in case of using HF checkpoints it should be doable to load on single GPU, pls refer to [inference example.](https://github.com/facebookresearch/llama-recipes/blob/main/examples/inference.py)

**Comment by deanhzm** [comment]
> > if you use my `inference.py` code instead.
> 
> > A modified model (`model.py`) below should works with a single GPU.
> 
> @cedrickchee I tried to use your code (model.py and inference.py) with 13B on Colab pro (I think with 40GB gpu ram). But I get the following errors.
> 
> `Traceback (most recent call last): File "inference.py", line 111, in <module> main( File "inference.py", line 90, in main generator = load( File "inference.py", line 66, in load model.load_state_dict(checkpoint, strict=False) File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1671, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for Transformer: size mismatch for tok_embeddings.weight: copying a param with shape torch.Size([32000, 2560]) from checkpoint, the shape in current model is torch.Size([32000, 5120]). size mismatch for layers.0.attention.wq.weight: copying a param with shape torch.Size([2560, 5120]) from checkpoint, the shape in current model is torch.Size([5120, 5120]). size mismatch for layers.0.attention.wk.weight: copying a param with shape torch.Size([2560, 5120]) from checkpoint, the shape in current model is torch.Size([5120, 5120]). size mismatch for layers.0.attention.wv.weight: copying a param with shape torch.Size([2560, 5120]) from checkpoint, the shape in current model is torch.Size([5120, 5120]). size mismatch for layers.0.attention.wo.weight: copying a param with shape torch.Size([5120, 2560]) from checkpoint, the shape in current model is torch.Size([5120, 5120]). size mismatch for layers.0.feed_forward.w1.weight: copying a param with shape torch.Size([6912, 5120]) from checkpoint, the shape in current model is torch.Size([13824, 5120]). size mismatch for layers.0.feed_forward.w2.weight: copying a param with shape torch.Size([5120, 6912]) from checkpoint, the shape in current model is torch.Size([5120, 13824]). size mismatch for layers.0.feed_forward.w3.weight: copying a param with shape torch.Size([6912, 5120]) from checkpoint, the shape in current model is torch.Size([13824, 5120]). size mismatch for layers.1.attention.wq.weight: copying a param with shape torch.Size([2560, 5120]) from checkpoint, the shape in current model is torch.Size([5120, 5120]).`
> 
> .. and size mismatch for many more layers.
> 
> Does the code work even with two separate pths (consolidated.00.pth, consolidated.01.pth)? Or do I need to change more?
> 
> Thanks.

How do you solve this problem?  I face the same situation. The 13B ckpt has 2 files and i want to run 13B on a single GPU.

**Comment by bp020108** [comment]
> > The 7B model works flawlessly, however the higher MP's are turning out to be an issue...
> 
> True. 13B MP is 2 and required 27GB VRAM. So it can run in a single A100 80GB or 40GB, but after modying the model.
> 
> Aside: if you don't know, Model Parallel (MP) encompasses both Pipeline Parallel (PP) and Tensor Parallel (TP). PP shards layers. TP shards each tensor. People always confuse them.
> 
> > After Fiddeling around a bit I think I came up with a solution, you can indeed try to run everything on a single GPU
> 
> The model by default is configured for distributed GPU (more than 1 GPU). A modified model (`model.py`) below should works with a single GPU. In addition, I also lowered the batch size to 1 so that the model can fit within VRAM.
> 
> ```python
> class ModelArgs:
>     dim: int = 512
>     n_layers: int = 8
>     n_heads: int = 8
>     vocab_size: int = -1
>     multiple_of: int = 256
>     norm_eps: float = 1e-5
> 
>     max_batch_size: int = 1 # <-- change this line from 32
> 
> # ...
> 
> class Attention(nn.Module):
>     def __init__(self, args: ModelArgs):
>         super().__init__()
> 
>         self.n_local_heads = args.n_heads // 1 # <-- change this. previous: args.n_heads // fs_init.get_model_parallel_world_size()
>         self.head_dim = args.dim // args.n_heads
> 
>         self.wq = nn.Linear( # <-- change line: previous: ColumnParallelLinear
>             args.dim,
>             args.n_heads * self.head_dim,
>             bias=False,
>             input_is_parallel=True, # <-- remove this line
>             init_method=lambda x: x, # <-- remove this line
>         )
>         self.wk = nn.Linear( # <-- change line: previous: ColumnParallelLinear
>             args.dim,
>             args.n_heads * self.head_dim,
>             bias=False,
>             input_is_parallel=True, # <-- remove this line
>             init_method=lambda x: x, # <-- remove this line
>         )
>         self.wv = nn.Linear( # <-- change line: previous: ColumnParallelLinear
>             args.dim,
>             args.n_heads * self.head_dim,
>             bias=False,
>             input_is_parallel=True, # <-- remove this line
>             init_method=lambda x: x, # <-- remove this line
>         )
>         self.wo = nn.Linear( # <-- change line: previous: RowParallelLinear
>             args.n_heads * self.head_dim,
>             args.dim,
>             bias=False,
>             input_is_parallel=True, # <-- remove this line
>             init_method=lambda x: x, # <-- remove this line
>         )
> 
> # ...
> 
> class FeedForward(nn.Module):
>     def __init__(
>         self,
>         dim: int,
>         hidden_dim: int,
>         multiple_of: int,
>     ):
>         super().__init__()
>         hidden_dim = int(2 * hidden_dim / 3)
>         hidden_dim = multiple_of * ((hidden_dim + multiple_of - 1) // multiple_of)
> 
>         self.w1 = nn.Linear( # <-- change this. previous: ColumnParallelLinear
>             dim, hidden_dim, bias=False, gather_output=False, init_method=lambda x: x
>         )
>         self.w2 = nn.Linear( # <-- change this. previous: RowParallelLinear
>             hidden_dim, dim, bias=False, input_is_parallel=True, init_method=lambda x: x
>         )
>         self.w3 = nn.Linear( # <-- change this. previous: ColumnParallelLinear
>             dim, hidden_dim, bias=False, gather_output=False, init_method=lambda x: x
>         )
> 
> # ...
> 
> class Transformer(nn.Module):
>     def __init__(self, params: ModelArgs):
>         super().__init__()
>         self.params = params
>         self.vocab_size = params.vocab_size
>         self.n_layers = params.n_layers
> 
>         self.tok_embeddings = nn.Embedding( # <-- change this. previous: ParallelEmbedding
>             params.vocab_size, params.dim
>         )
> 
>         self.layers = torch.nn.ModuleList()
>         for layer_id in range(params.n_layers):
>             self.layers.append(TransformerBlock(layer_id, params))
> 
>         self.norm = RMSNorm(params.dim, eps=params.norm_eps)
>         self.output = nn.Linear( # <-- change this. previous: ColumnParallelLinear
>             params.dim, params.vocab_size, bias=False
>         )
> 
> # ...
> ```
> 
> Modify those lines I mentioned in the code above. Basically, we removed all model parallel codes to make it work.
> 
> Edit 1: I forgot to include the `example.py` modifications, here you go in case you need it: https://github.com/cedrickchee/llama/blob/main/chattyllama/inference.py
> 
> Edit 2: No `torchrun` needed for this port. README says: "The provided `example.py` can be run on a single or multi-gpu node with `torchrun`"

do you know what would be NPU layers number / batch size/ context size for A100 GPU 80GB with 13B (MODEL_BASENAME = "llama-2-13b-chat.Q4_K_M.gguf") ? 



MODELS_PATH = "./models"

# Can be changed to a specific number
INGEST_THREADS = os.cpu_count() or 24

# Define the Chroma settings
CHROMA_SETTINGS = Settings(
    anonymized_telemetry=False,
    is_persistent=True,
)

# Context Window and Max New Tokens
CONTEXT_WINDOW_SIZE = 4096
MAX_NEW_TOKENS = CONTEXT_WINDOW_SIZE  # int(CONTEXT_WINDOW_SIZE/4)

#### If you get a "not enough space in the buffer" error, you should reduce the values below, start with half of the original values and keep halving the value until the error stops appearing

N_GPU_LAYERS = 50 # Llama-2-70B has 83 layers
N_BATCH = 512

### From experimenting with the Llama-2-7B-Chat-GGML model on 8GB VRAM, these values work:
# N_GPU_LAYERS = 20
# N_BATCH = 512
