### ISSUE TITLE
Changing the $MP?

### ISSUE THREAD

**Issue by jacklxc** [facebookresearch/llama-recipes#174]
Our server has A100\*2 (80GB), A6000\*2 (49GB), and A5000\*2 (24GB). Currently, without any modification, we can only run at most the 30B model, because by default, the 65B model requires MP=8. Can we maximize each GPU's usage so that the 65B can run on these 6 GPUs?

**Comment by jspisak** [comment]
transferring to llama-recipes and closing in the mean time..
