### ISSUE TITLE
FSDP+PEFT runtime errors 

### ISSUE THREAD

**Issue by moseshu** [facebookresearch/llama-recipes#184]
```
system info:
torch=2.0.1
transformers==4.31.0
peft=0.4.0
cuda=11.7
it raise error.below
how to solve this?

RuntimeError: setStorage: sizes [4096, 64], strides [64, 1], storage offset 0, and itemsize 4 requiring a storage size of 1048576 are out of bounds for storage of size 0
```

**Comment by HamidShojanazeri** [comment]
@moseshu can you pls make sure to use Pytorch nightlies for PEFT+FSDP.

**Comment by moseshu** [comment]
> Pytorch nightlies
if my cuda version is 11.8 ,is it ok?I tried to download Pytorch nightlies. there is nothing missing. Thanks ,I need to check it

**Comment by moseshu** [comment]
> @moseshu can you pls make sure to use Pytorch nightlies for PEFT+FSDP and please add the repro steps.

pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu117 
is this correct?
