### ISSUE TITLE
How to turn off ethical/legal/safe check in llama-2 models?

### ISSUE THREAD

**Issue by rsaxena-rajat** [facebookresearch/llama-recipes#187]
### 🚀 The feature, motivation and pitch

I am using llama-2-7b-chat model to generate JSON objects with few-shot inference using the llama prompt template. If the model gets something like "allow gambling" in the prompt, it refuses to answer (i.e. it does not generate the JSON object). 

The behavior cannot be changed even with system prompt.

Is there a solution to switch off this check and reduce the refusal rates for prompts?

### Alternatives

None

**Comment by HamidShojanazeri** [comment]
@rsaxena-rajat these are the built-in safety features for the chat models and recommended to be used, so we wont encourage any changes there. But if you feel there is any concern around unnecessary content moderation pls open an issue on the llama repo.
