### ISSUE TITLE
weight_decay is not used in `finetuning.py`

### ISSUE THREAD

**Issue by shijie-wu** [facebookresearch/llama-recipes#191]
### System Info

n/a

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

weight_decay is not used in `finetuning.py`
https://github.com/facebookresearch/llama-recipes/blob/c38bf5bdd370ceb93e71cfec1a07b0885a57e3ec/src/llama_recipes/finetuning.py#L222-L235 even though it's part of the config https://github.com/facebookresearch/llama-recipes/blob/c38bf5bdd370ceb93e71cfec1a07b0885a57e3ec/src/llama_recipes/configs/training.py#L18

### Error logs

n/a

### Expected behavior

`weight_decay` should be passed into the optimizer. on a related note, since it's hard-coded to 0, is it recommended to set `weight_decay` to 0?

**Comment by mreso** [comment]
@shijie-wu Good catch, it is supposed to be forwarded to the optimizer. Happy to review a PR if would like to contribute this!
