### ISSUE TITLE
Example prompts of chat and pre-trained variants for document Q&A tasks?

### ISSUE THREAD

**Issue by abhijithnair1** [facebookresearch/llama-recipes#2]
I am trying to see if I can use the model with RetrievalQA tasks (

In other models like `falcon-7b instruct` I used to provide a prompt like this,
```
Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}

Question: {question}
Answer:
```

I am bit confused if I should use pre-trained or chat variant for document QA tasks. In the huggingface model card there was mention of using chat variant for Q&A tasks since it's instruction tuned.

Can you provide an example prompt I can send for chat variant if it can be used for document Q&A tasks? I couldn't find much in the repo for this task.

**Comment by chauhang** [comment]
Please see the [Chat completion ](https://github.com/facebookresearch/llama-recipes/blob/main/inference/chat_completion.py) example:

**Comment by abhijith63** [comment]
> Please see the [Chat completion ](https://github.com/facebookresearch/llama-recipes/blob/main/inference/chat_completion.py) example, usage steps [here](https://github.com/facebookresearch/llama-recipes/blob/main/inference/inference.md)

Given it a review, but it's bit unclear on how to format it on my usecase. Would appreciate if someone can provide some insights on how to format the prompt (that I have above) which actually works with chat variant of llama 2. Thanks

**Comment by HamidShojanazeri** [comment]
@abhijithnair1 it might be useful to look at `ConversationalPipeline` in HF transformers, following code snippet might be helpful  as an example how to arrange your inputs.

```
 model = LlamaForCausalLM.from_pretrained(model_name)
    tokenizer = LlamaTokenizer.from_pretrained(model_name, use_fast = False) # need to update the fast tokenizer file
    chatbot = ConversationalPipeline(model=model,tokenizer = tokenizer, device = 0, max_length=435,temperature=0.6,top_p=0.9)
    conversation = Conversation("What is so great about #1?", past_user_inputs = ["I am going to Paris, what should I see?"], generated_responses=["Paris, the capital of France, is known for its stunning architecture, art museums, historical landmarks, and romantic atmosphere. Here are some of the top attractions to see in Paris:1. The Eiffel Tower: The iconic Eiffel Tower is one of the most recognizable landmarks in the world and offers breathtaking views of the city.2. The Louvre Museum: The Louvre is one of the world's largest and most famous museums, housing an impressive collection of art and artifacts, including the Mona Lisa.3. Notre-Dame Cathedral: This beautiful cathedral is one of the most famous landmarks in Paris and is known for its Gothic architecture and stunning stained glass windows.These are just a few of the many attractions that Paris has to offer. With so much to see and do, it's no wonder that Paris is one of the most popular tourist destinations in the world."])
    conversation = chatbot(conversation)
    print(conversation.generated_responses[-1])
    
```

**Comment by abhipn** [comment]
@HamidShojanazeri @chauhang Thanks for this, I have a follow up question. The model that I'm trying to finetune is "Llama-2-7b-chat-hf" instruction tuned variant.

I have a dataset of question and answers, it's a custom dataset.

To finetune a Llama 2 - chat model, I assume I have to use the same prompt that you have used for the finetuning the model. **Can you confirm if below prompt would be ideal for finetuning the already finetuned variant of llama 2?**

```
[INST]<<SYS>>
You are a helpful, respectful and honest assistant. Always provide accurate answer based on the context given below. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.<</SYS>>

 [/INST][INST] {question} </s>[/INST][INST] {answer} </s>[/INST]
```

**Comment by abhijithnair1** [comment]
@HamidShojanazeri @chauhang Thanks for this, I have a follow up question. The model that I'm trying to finetune is "Llama-2-7b-chat-hf" instruction tuned variant.

I have a dataset of question and answers, it's a custom dataset.

To finetune a Llama 2 - chat model, I assume I have to use the same prompt that you have used for the finetuning the model. **Can you confirm if below prompt would be ideal for finetuning the already finetuned variant of llama 2?**

```
[INST]<<SYS>>
You are a helpful, respectful and honest assistant. Always provide accurate answer based on the context given below. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.<</SYS>>

 [/INST][INST] {question} </s>[/INST][INST] {answer} </s>[/INST]
```

**Comment by HamidShojanazeri** [comment]
yes, mostly and you can refer to this [doc](https://huggingface.co/blog/llama2#how-to-prompt-llama-2) just make sure that there should be a space between [INST] <<SYS>>.

**Comment by abhijithnair1** [comment]
> yes, mostly and you can refer to this [doc](https://huggingface.co/blog/llama2#how-to-prompt-llama-2) just make sure that there should be a space between` [INST] <<SYS>>`.

Thank you!. Can you also please confirm once after training and during inference, should I remove the answer part and provide the below prompt to get the response back right?

```
 [INST] <<SYS>>
You are a helpful, respectful and honest assistant. Always provide accurate answer based on the context given below. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.<</SYS>>

 [/INST][INST] {question} </s>[/INST]
```

**Comment by HamidShojanazeri** [comment]
yes, just note this for the fine-tuned/ chat model. So it can be that + adding context if needed, one way to think about it is the code snippet I shared above, as this has been added to HF tokenizer in general [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/tokenization_llama.py#L334), where you need to use `_build_conversation_input_ids`, where in HF stack it has been used with `Conversation` as showed above. 

You can decouple this from `ConversationalPipeline` just need to a bit of digging into code stack.

**Comment by abhijithnair1** [comment]
> @HamidShojanazeri @chauhang Thanks for this, I have a follow up question. The model that I'm trying to finetune is "Llama-2-7b-chat-hf" instruction tuned variant.
> 
> I have a dataset of question and answers, it's a custom dataset.
> 
> To finetune a Llama 2 - chat model, I assume I have to use the same prompt that you have used for the finetuning the model.
> 
> **Can you confirm if below prompt would be ideal for finetuning the already finetuned variant of llama 2?**
> 
> ```
> [INST]<<SYS>>
> You are a helpful, respectful and honest assistant. Always provide accurate answer based on the context given below. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.
> 
> If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.<</SYS>>
> 
>  [/INST][INST] {question} </s>[/INST][INST] {answer} </s>[/INST]
> ```



> yes, mostly and you can refer to this [doc](https://huggingface.co/blog/llama2#how-to-prompt-llama-2) just make sure that there should be a space between` [INST] <<SYS>>`.

thanks for sharing additional info. the earlier link you shared is https://huggingface.co/blog/llama2#how-to-prompt-llama-2. but the prompt I am bit confused on these below two variants?

Prompt 1:

```
[INST]<<SYS>>
You are a helpful, respectful and honest assistant. Always provide accurate answer based on the context given below. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.<</SYS>>

 [/INST][INST] {question} </s>[/INST][INST] {answer} </s>[/INST]
```

or 

Prompt2:

```
<s>[INST] <<SYS>>
You are a helpful, respectful and honest assistant. Always provide accurate answer based on the context given below. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
<</SYS>>

{question} [/INST] {answer} </s>
```

Which one should I use for finetuning the chat varaint?

**Comment by HamidShojanazeri** [comment]
referenced in the same doc, following should help, from what you share prompt 2 seems correct.

```
<s>[INST] <<SYS>>
{{ system_prompt }}
<</SYS>>

{{ user_msg_1 }} [/INST] {{ model_answer_1 }} </s>\
<s>[INST] {{ user_msg_2 }} [/INST] {{ model_answer_2 }} </s>\
<s>[INST] {{ user_msg_3 }} [/INST]

```

**Comment by abhijithnair1** [comment]
> referenced in the same doc, following should help, from what you share prompt 2 seems correct.
> 
> ```
> <s>[INST] <<SYS>>
> {{ system_prompt }}
> <</SYS>>
> 
> {{ user_msg_1 }} [/INST] {{ model_answer_1 }} </s>\
> <s>[INST] {{ user_msg_2 }} [/INST] {{ model_answer_2 }} </s>\
> <s>[INST] {{ user_msg_3 }} [/INST]
> ```

Thank you, I'll try to run my experiment and see how it goes.

**Comment by HamidShojanazeri** [comment]
sure let us know how it goes.

**Comment by abhijithnair1** [comment]
> sure let us know how it goes.

That worked. I was able to use the same prompt to finetune the chat variant of Llama 2. I am getting some good results compared to finetuning it on the base model.

**Comment by marclove** [comment]
@HamidShojanazeri Does this format mean that when further fine-tuning the chat model, we should we be fine-tuning with the completion starting with a single space?
