### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_recipes'

### ISSUE THREAD

**Issue by qing-yuan233** [facebookresearch/llama-recipes#208]
### 🚀 The feature, motivation and pitch

when i cd llama-recipe and do torchrun xxx，error：ModuleNotFoundError: No module named 'llama_recipes'
how to solve？

**Comment by jveronvialard** [comment]
Have you tried [install with pip](https://github.com/facebookresearch/llama-recipes#install-with-pip)?

**Comment by polym** [comment]
Try this in the llama-recipe folder.

```
pip install -e .
```

**Comment by qing-yuan233** [comment]
I have already solved this problem. In the current main branch, the directory location is incorrect, and it is necessary to replace src/llama_ Place the recipes in the previous directory, and then place the finetuning. py in the previous directory

**Comment by mreso** [comment]
@qing-yuan233 yes, we changes the directory structure for the packaging process. Easiest is to run installation from source as pointed out above. Closing this as you're solved your problem.
