### ISSUE TITLE
Cannot find config.json in llama-2-13b model

### ISSUE THREAD

**Issue by sdx0112** [facebookresearch/llama-recipes#21]
I am trying to fine tune the newly released llama 2 model with this repo. Here is my code:
`torchrun --nnodes 1 --nproc_per_node 4  llama_finetuning.py --enable_fsdp --use_peft --peft_method lora --model_name ../llama/llama-2-13b/ --pure_bf16 --output_dir ../llama_2_lora_test/`

Got the following error:
`OSError: ../llama/llama-2-13b/ does not appear to have a file named config.json. Checkout 'https://huggingface.co/../llama/llama-2-13b//main' for available files.`

Here are all the files in the llama 2 model folder:
![image](https://github.com/facebookresearch/llama-recipes/assets/8717860/84b63b52-6b50-473e-909c-83a59e31e565)

**Comment by chauhang** [comment]
@sdx0112 You need to convert the model to HF format first to use with the llama-recipes. Please use the conversion steps, see https://github.com/facebookresearch/llama-recipes/issues/3#issuecomment-1641647361

**Comment by sdx0112** [comment]
Thanks @chauhang ,but I got another error saying there is no tokenizer in the llama-2 folder.
![image](https://github.com/facebookresearch/llama-recipes/assets/8717860/f1299fee-f7bb-47f4-8f87-efb2897de129)

Actually there is no such tokenizer file. The model weights can be produced.
![image](https://github.com/facebookresearch/llama-recipes/assets/8717860/765704fc-7ec8-425b-9b01-ba6a76986640)

**Comment by HamidShojanazeri** [comment]
@sdx0112 are you using HF weights or got the weights from Meta? if meta version then tokenizer leaves in the parent folder --> `parent folder (tokenizer.model) / 13B`

**Comment by HamidShojanazeri** [comment]
seems this has been resolved as no further updates.
