### ISSUE TITLE
Running examples/finetuning.py problem

### ISSUE THREAD

**Issue by Lucien20000118** [facebookresearch/llama-recipes#214]
I'm trying to use the finetuning example. I installed the provided installations with pip.
`pip install --extra-index-url https://download.pytorch.org/whl/test/cu118 llama-recipes`
And I saw it is necessary to install the Pytorch-nightly version.
`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118`

And I ran the finetuning example `torchrun --nnodes 1 --nproc_per_node 2  examples/finetuning.py --enable_fsdp --model_name Llama-2-7b-hf --use_peft --peft_method lora --output_dir fine-tune-7b   `

`[2023-09-19 13:35:12,994] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[2023-09-19 13:35:13,028] torch.distributed.run: [WARNING] 
[2023-09-19 13:35:13,028] torch.distributed.run: [WARNING] *****************************************
[2023-09-19 13:35:13,028] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
[2023-09-19 13:35:13,028] torch.distributed.run: [WARNING] *****************************************
[W socket.cpp:686] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - 內容中所要求的位址不正確。).
FalseFalse

===================================BUG REPORT======================================================================BUG REPORT===================================

D:\conda_env\llama-recipe\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
D:\conda_env\llama-recipe\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================================================================================================

The following directories listed in your path were found to be non-existent: {WindowsPath('D')}The following directories listed in your path were found to be non-existent: {WindowsPath('D')}

D:\conda_env\llama-recipe\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: D:\conda_env\llama-recipe did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
D:\conda_env\llama-recipe\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: D:\conda_env\llama-recipe did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...

The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}  

DEBUG: Possible options found for libcudart.so: set()DEBUG: Possible options found for libcudart.so: set()

CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md

CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.mdCUDA SETUP: Loading binary D:\conda_env\llama-recipe\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...

CUDA SETUP: Loading binary D:\conda_env\llama-recipe\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...argument of type 'WindowsPath' is not iterable

argument of type 'WindowsPath' is not iterableCUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.

CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variableCUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.

CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/nullCUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable

CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrcCUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null

CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a      

CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.shCUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc

CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.  

CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/localCUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh

CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
Traceback (most recent call last):
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local  File "D:\conda_env\llama-recipe\lib\site-packages\transformers\utils\import_utils.py", line 1184, in _get_module`

I am in the Windows system, but it desired the Linux system package.
The problem I encountered previously, I couldn't resolve it at that time, and instead, I had to reconstruct a new environment to make it work properly. However, after installing the recipe, I encountered the same issue again.
Has anyone faced the same issue?

**Comment by Lucien20000118** [comment]
I found that if I ran the installation code, it would come out with the same problem. Even I do not install the nightly version.

**Comment by polym** [comment]
The issue appears to be related to CUDA. If you are using conda to manage your environment, you can install the CUDA dependency with conda.

```
conda install -c nvidia cudatoolkit nvidia-nvcc
```

**Comment by Lucien20000118** [comment]
> @Lucien20000118 The issue appears to be related to CUDA. If you are using conda to manage your environment, you can install the CUDA dependency with conda.
> 
> ```
> conda install -c nvidia cudatoolkit nvidia-nvcc
> ```

@polym Thanks for your reply. I tried this command, but conda has no this package to install.
And as I know that the pytoch installation will install the cudatoolkit too?

**Comment by polym** [comment]
@Lucien20000118 Sorry for the wrong command I provided. Right one is `conda install -c nvidia cudatoolkit cuda-nvcc`. BTW, can you find  libcudart.so in your system path?

**Comment by Lucien20000118** [comment]
> @Lucien20000118 Sorry for the wrong command I provided. Right one is `conda install -c nvidia cudatoolkit cuda-nvcc`. BTW, can you find libcudart.so in your system path?

@polym Thanks for your reply.
I think because I'm in the Windows system, I only have the cudart.dll. Is it right?

**Comment by Lucien20000118** [comment]
I changed to use Ubuntu to solve this problem. Thanks!
