### ISSUE TITLE
Train LLAMA 2 tokenizer from scratch 

### ISSUE THREAD

**Issue by lfoppiano** [facebookresearch/llama-recipes#239]
Hello, 
   I'm trying to train the same tokenizer (BPE with SentencePiece) and apply the same strategy as you did in your approach. 
I wonder if there is code that does that already available somewhere in this repository. 
I've been searching but could not find anything. It seems that most of the notebooks assume we load the llma2 model. 

Thank you in advance
Luca

**Comment by HamidShojanazeri** [comment]
@lfoppiano thans Luca, unfortunately we dont have any code for training tokenizer in this repo. This [HF post may help](https://huggingface.co/learn/nlp-course/chapter6/2).

**Comment by cyberiumchain** [comment]
That HF post says nothing about the tokenizer.model. Can you explain about how to generate the model file?

**Comment by lfoppiano** [comment]
@cyberiumchain In principle if you use SentencePiece and the BPE encoder you should obtain the same result... but it's hard to know without any code...

**Comment by AI-Guru** [comment]
I am curious too! Is there really no code for creating a Llama tokenizer?
