### ISSUE TITLE
Pipeline Parallel for fine-tuning

### ISSUE THREAD

**Issue by taowangcheng** [facebookresearch/llama-recipes#241]
### 🚀 The feature, motivation and pitch

I want to know how to full-parameter fine-tune a llama2 model in data parallel combined with pipeline parallel. Especially fine-tuning a llama2 model in pipeline parallel. Do you have any examples?

**Comment by HamidShojanazeri** [comment]
@taowangcheng we dont have any pipeline parallel example here but is there any specific reason you are interested in that workflow? overall for pipeline parallelism you might want to check this [repo ](https://github.com/pytorch/PiPPy).

**Comment by taowangcheng** [comment]
I am doing some research about accelerating LLMs, so I need pipeline parallel examples.

**Comment by HamidShojanazeri** [comment]
Sounds good, I will close this issue and if would be great if you could give a try to pipeline repo I linked above and pls open an issue there is ran into any. I also collaborate on that repo too.
