### ISSUE TITLE
Unable to download llama pre training model

### ISSUE THREAD

**Issue by surviveMiao** [facebookresearch/llama-recipes#244]
### 🚀 The feature, motivation and pitch

How can I solve the problem of not being able to apply for the pre trained model of llama2 on the official website or huggingface?

**Comment by HamidShojanazeri** [comment]
@surviveMiao I hope this help, access to llama weights on[ HF model hub](https://huggingface.co/meta-llama), there is a [form ](https://ai.meta.com/resources/models-and-libraries/llama-downloads/)you need to fill up and within a few mins you will get access. Any model name on the hub *without -hf* is Meta weight. 

Then in your terminal, use `5- huggingface-cli login #your API Token` to login first, these models are gated and need your HF API token to let you download.
