### ISSUE TITLE
Docs and assertion out of date regarding pytorch 2.1 fsdp/lora

### ISSUE THREAD

**Issue by jph00** [facebookresearch/llama-recipes#246]
### System Info

N/A

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

The docs currently state that a prerelease version of PyTorch is required for fsdp with lora, and an assertion in finetuning.py checks that a prerelease is installed. However, the newly released PyTorch 2.1 works correctly (I just tested it) so the assertion should be updated to also allow v2.1, and the docs should mention that too.

### Error logs

N/A

### Expected behavior

See above.

**Comment by HamidShojanazeri** [comment]
thanks @jph00 thats right we will update the code.
