### ISSUE TITLE
Add Flash Attention 2 Support

### ISSUE THREAD

**Issue by rajveer43** [facebookresearch/llama-recipes#248]
Feature request

Flash Attention 2 is a library that provides attention operation kernels for faster and more memory efficient inference and training: https://github.com/Dao-AILab/flash-attention

**Comment by HamidShojanazeri** [comment]
@rajveer43 this has been added natively to Pytorch so if you are latest pytroch, you most probably is using it through [SDPA](https://pytorch.org/tutorials/intermediate/scaled_dot_product_attention_tutorial.html#nestedtensor-and-dense-tensor-support), on recipe we also have integration with [HF through optimum](https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/finetuning.py#L110).
