### ISSUE TITLE
13B Fine-tuning GPU requirements

### ISSUE THREAD

**Issue by generalsvr** [facebookresearch/llama-recipes#25]
How many A100 GPUs (40GB) required to tune 13B model ( full parameter )? I want to train llama2 for new language, so lora is not the best option

**Comment by HamidShojanazeri** [comment]
@generalsvr as per my experiments 13B with 8xA100 80 GB reserved memory was 48 GB per GPU, with bs=4, so my estimation is we should be able to run it with 16x A100 40 GB (2 nodes) for a reasonable batch size.

**Comment by s1ghhh** [comment]
Based on my experience, A100 40G*4 and 240G of CPU RAM are the minimum requirements for fine-tuning the model finetune13b when using fsdp offload and flash attention. A more reasonable choice would be A100 40G*8, in which case you won't need to use offload.

**Comment by HamidShojanazeri** [comment]
we have added the support through our integration with HF that can be set from [here](https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/configs/training.py#L36), and in effect from [here](https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/finetuning.py#L109).
