### ISSUE TITLE
https://github.com/facebookresearch/llama-recipes/pull/260

### ISSUE THREAD

**Issue by johnbwilliams** [facebookresearch/llama-recipes#261]
### System Info

Jupyter Notebook. The version of the notebook server is: 6.5.4

Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

This following Jupyter cell fails because pypdf is not installed:

#from langchain import document_loaders
from langchain.document_loaders import PyPDFLoader
loader = PyPDFLoader("https://arxiv.org/pdf/2307.09288.pdf")
docs = loader.load()

### Error logs

expected error trace from reqquired missing module pypdf

### Expected behavior

no errors

**Comment by jeffxtang** [comment]
@HamidShojanazeri can you please merge the PR #260? that'll fix the issue.

**Comment by HamidShojanazeri** [comment]
@johnbwilliams this should have been fixed as PR got merged.
