### ISSUE TITLE
Provide a docker file? 

### ISSUE THREAD

**Issue by s95huang** [facebookresearch/llama-recipes#29]
Hello, 
Thank you for providing the LLAMA-recipes and LLAMA V2 model.
I have encounted the following error as reported in issure #15 .
``` 
 File "/home/anaconda3/envs/drive_llama2/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 166, in scale
    assert outputs.is_cuda or outputs.device.type == 'xla'
```

I would like to ask would it be possible to release a docker file?

**Comment by HamidShojanazeri** [comment]
Thanks @s95huang  for opening this issue, it has been addressed in this PR https://github.com/facebookresearch/llama-recipes/pull/33.

On the docker file, its is planned will keep you posted once ready.

**Comment by s95huang** [comment]
Thank you, PR#33 fixed my problem.
I will close this issue
