### ISSUE TITLE
HF conversion instructions are incorrect

### ISSUE THREAD

**Issue by iibw** [facebookresearch/llama-recipes#3]
The HF conversion instructions [here](https://github.com/facebookresearch/llama-recipes#model-conversion-to-hugging-face) say to run a pip command and then cd into the transformers directory. The transformers directory does not exist after running that command though.

**Comment by emanuelevivoli** [comment]
I have changed some parts **(only in the _main_ part)** of the `convert_llama_weights_to_hf.py` so it can easily maps `model_size` to `folder_name`:
```python
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input_dir",
        help="Location of LLaMA weights, which contains tokenizer.model and model folders",
    )
    parser.add_argument(
        "--model_size",
        choices=["7B", "7Bf", "7B-c", "13B", "13Bf", "13B-c", "30B", "65B", "70B", "70Bf", "70B-c", "tokenizer_only"],
    )
    parser.add_argument(
        "--output_dir",
        help="Location to write HF model and tokenizer",
    )
    parser.add_argument("--safe_serialization", type=bool, help="Whether or not to save using `safetensors`.")
    args = parser.parse_args()
    # Map the model size to the model name
    mapper = {
        "7B": "llama-2-7b",
        "7B-c": "llama-2-7b-chat",
        "13B": "llama-2-13b",
        "13B-c": "llama-2-13b-chat",
        "70B": "llama-2-70b",
        "70B-c": "llama-2-70b-chat",
    }
    model_name = mapper[args.model_size]
    if args.model_size != "tokenizer_only":
        write_model(
            model_path=args.output_dir,
            input_base_path=os.path.join(args.input_dir, model_name),
            model_size=args.model_size,
            safe_serialization=args.safe_serialization,
        )
    spm_path = os.path.join(args.input_dir, "tokenizer.model")
    write_tokenizer(args.output_dir, spm_path)


if __name__ == "__main__":
    main()
```

This is because I want to keep filenames as `llama-2-7b` and `llama-2-7B-chat` as I download them with the script.

**Comment by iibw** [comment]
That's useful, thanks.

I was also getting this warning:
```
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
```

I looked into it and this message is displayed when a `LlamaTokenizer` object is created with the parameter `legacy=True`. Given that the README says to use `convert_llama_weights_to_hf.py` as it is, I guess we don't have to worry about it and we use the legacy tokenizer. I don't know enough about the tokenizer to know if it's ok to mark `legacy=False`. I'd rather not have this bug though so if it's ok to mark `legacy=False`, I'd appreciate someone mentioning it.

**Comment by chauhang** [comment]
Please use the latest Transformer 4.31.0 release which includes the updated conversion scripts. Will update the docs to match

 ```
pip freeze | grep transformers ## verify it is version 4.31.0 or higher
git clone git@github.com:huggingface/transformers.git
cd transformers
pip install protobuf
python src/transformers/models/llama/convert_llama_weights_to_hf.py \
    --input_dir /path/to/downloaded/llama/weights --model_size 7B --output_dir /output/path
```
    
Alternatively you can also download the converted weights from the HuggingFace hub: https://huggingface.co/meta-llama

**Comment by RunsenXu** [comment]
Hi I wonder which version of Transformers should I use for the converted weights I directly download from https://huggingface.co/meta-llama?

**Comment by chauhang** [comment]
You need Transformers 4.31.0 or higher. Follow the setup steps from the [readme](https://github.com/facebookresearch/llama-recipes/tree/main#requirements) and see the [requirements.txt](https://github.com/facebookresearch/llama-recipes/blob/main/requirements.txt#L12)

**Comment by iibw** [comment]
> That's useful, thanks.
> 
> I was also getting this warning:
> 
> ```
> You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
> ```
> 
> I looked into it and this message is displayed when a `LlamaTokenizer` object is created with the parameter `legacy=True`. Given that the README says to use `convert_llama_weights_to_hf.py` as it is and you get this message from loading their `tokenizer.model`, I guess we don't have to worry about it and we use the legacy tokenizer.
> 
> I don't know enough about the tokenizer to know if it's ok to mark `legacy=False`. I'd rather not have this bug so if it's ok to mark `legacy=False`, I'd appreciate someone mentioning it.

I have an update to this. Meta's official HF repository has `legacy=False` in [their tokenizer's config](https://huggingface.co/meta-llama/Llama-2-70b-chat-hf/blob/main/tokenizer_config.json) so I guess we can set `legacy=False` too.

**Comment by iibw** [comment]
Also the transformers script to convert to HF sets all tokens to be normalized but the tokenizer configs have `"normalized": false` set
