### ISSUE TITLE
Minimum Required Memory to Fine Tune LLama-70B

### ISSUE THREAD

**Issue by Raed-Mughaus** [facebookresearch/llama-recipes#332]
I'm trying to fine tune llama-2-70b using 8 x 48GB GPUs. Both FSDP & PEFT options are enabled.

The training works fine until all epochs are done. And then I get a CUDA OOM error, +before this error a message about saving the model appears.

Is there any one who managed to fine tune llama-70B using 8 x 48 GB GPUs?

**Comment by bilaalmirza** [comment]
The minimum required memory to fine-tune LLama-70B depends on the specific training data and the model's complexity, typically ranging from 8GB to 16GB.

**Comment by AliceShen122** [comment]
> 微调LLama-70B所需的最小内存取决于具体的训练数据和模型的复杂度，通常在8GB到16GB之间。

这个是怎么算的呢？

**Comment by wukaixingxp** [comment]
Hi! I think it depends on the fine-tuning method. Here is a [summary table ](https://github.com/hiyouga/LLaMA-Factory?tab=readme-ov-file#hardware-requirement)you can refer to.  [This blog](https://blog.eleuther.ai/transformer-math/) also has a great tutorial about the calculations. Let me know if you have any problems!
