### ISSUE TITLE
Partial Parameter Fine-Tuning

### ISSUE THREAD

**Issue by thanhsang298** [facebookresearch/llama-recipes#340]
Hi guys, thanks for the great resource. 
I wanna finetune Llama2-7b model for classification task. 
I wanna freeze all the Transformers block params and replace classification head.
How i can use this repo for this purpose, thank you :D

**Comment by HamidShojanazeri** [comment]
@thanhsang298 sorry for the late reply, I haven't tried it but you might be able to use [LlamaForSequenceClassification](https://huggingface.co/docs/transformers/main/en/model_doc/llama2#transformers.LlamaForSequenceClassification). However you can fine-tune it for a classification task by formatting your dataset accordingly, let say you wanna do a sentiment analysis, for example : "Review: [movie review] Sentiment:", where the model is expected to generate "positive" or "negative" after the "Sentiment:" prompt. Then you can fine-tune it with this labeled dataset. Hope that helps.

In terms of un/freezing layers, if you are in single gpu then you can use normal methods, something like

```
for param in model.parameters():
    param.requires_grad = False
    
for param in model.transformer.h[-1].parameters():
    param.requires_grad = True
    
  ```
  
  but if you are using FSDP, working on this option [here](https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/configs/training.py#L33), it requires further testing though.

**Comment by thanhsang298** [comment]
thank for your reply
