### ISSUE TITLE
how to fine-tune Llama Guard with my own data?

### ISSUE THREAD

**Issue by dongdql** [facebookresearch/llama-recipes#347]

**Comment by HamidShojanazeri** [comment]
@dongdql do you have the preprocessing of your data already in place?

**Comment by albertodepaola** [comment]
Hi @dongdql! 

For fine tuning examples using your own data please take a look at our examples here in the repo and the reference Readme: https://github.com/facebookresearch/llama-recipes/blob/main/src/llama_recipes/data/llama_guard/README.md
In the same directory you can find a script that helps building the correct dataset format from basic user prompts and appropriate labels.

Feel free to reopen if you have further questions!

**Comment by bilal12367** [comment]
Hi @albertodepaola 
Yea hey mate, page is not working anymore which you've mentioned. Can't even find the article in those repos. 
Would you mind posting the link again.

**Comment by dongdql** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，我将尽快给你回复。谢谢~

**Comment by IgorKasianenko** [comment]
Hi @bilal12367 
The repo was restructured. Please find the relevant fine tuning instructions here https://github.com/meta-llama/llama-cookbook/tree/main/getting-started/responsible_ai/llama_guard and latest torch tune example here https://github.com/meta-llama/llama-cookbook/blob/main/getting-started/responsible_ai/llama_guard/llama_guard_finetuning_multiple_violations_with_torchtune.ipynb

If you facing any issues please open a new issue with the description of the problem or suggestion.

**Comment by sneha-rudra** [comment]
HI @IgorKasianenko  this notebook https://github.com/meta-llama/llama-cookbook/blob/main/getting-started/responsible_ai/llama_guard/llama_guard_finetuning_multiple_violations_with_torchtune.ipynb
seems to have several dependency issues. Could you please try running all the cells once and check? I’m trying to run it on a Colab T4 GPU setup.

**Comment by dongdql** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，邮件已收到，我将尽快给你回复。谢谢~

**Comment by IgorKasianenko** [comment]
Hi @sneha-rudra ,
The notebook author uses Total GPU Memory: 160 GB (4x 40 GB) of A400 GPU. I was able to reproduce it with 8x24 GB GPU memory. Colab T4 may require smaller batch size and longer run time to reproduce the results. 
Please feel free open new issue with more technical details, as well as error logs if you have any.
