### ISSUE TITLE
What is the difference between quickstart.ipynb and llama_finetuning.py?

### ISSUE THREAD

**Issue by daegonYu** [facebookresearch/llama-recipes#35]
What is the difference between quickstart.ipynb and llama_finetuning.py? Is llama_finetuning.py more precise?

**Comment by HamidShojanazeri** [comment]
@daegonYu quick start notebook make use of HF trainer and llama-finetuning.py uses the training loop provided in utils/train_utils.py, in essence both should have feature parity its just the matter of preference.
