### ISSUE TITLE
Multi-node fine-tuning llama2 70b

### ISSUE THREAD

**Issue by jens5588** [facebookresearch/llama-recipes#352]
Hello,
currently, I want to finetune llama2 70b with my own dataset. I work on a slurm cluster and have access to 2 nodes, each having 8 A100(40GB). The context in my data is relatively long, so I want to have a max length of 4096. What would be the best practice to finetune my data with lora (not qlora) with batch_size 1? I have tried with multi_node.slurm for lora finetuning, it works for 7B. It seems to have the implicit assumption that all layers for a model can be loaded completely on a GPU or a node. Is it possible to adapt the slurm and finetuning scripts in llama-recipes so that I can distribute all layers into 16 GPUs evenly on two nodes and then finetune with batch_size 1, bf16?
Thanks in advance
Kind regards

**Comment by HamidShojanazeri** [comment]
@jens5588 thanks for your interest and the context, the assumption is it should be able to partition your model over 16 GPUs with FSDP, we have added the `--low_cpu_fsdp` this would help to avoid loading multiple copies of the model into CPU (only on rank0 then sync to all other ranks), so it would be a command like below in the slurm script. Also passing `--pure_bf16` would help to run the training in bf16. Please let me know how it goes and if need further help.

```
srun  torchrun --nproc_per_node 8 --rdzv_id $RANDOM --rdzv_backend c10d --rdzv_endpoint $head_node_ip:29500 examples/finetuning.py  --enable_fsdp --use_peft --peft_method lora --output_dir ./lora_model_save_dir --low_cpu_fsdp --pure_bf16

```

**Comment by jens5588** [comment]
@HamidShojanazeri, it works, and thanks for your quick response. And I have another issue regarding SLURM. I show you my adapted SLURM script based on multi_node.slurm
#!/bin/bash
#SBATCH --job-name=llama_recipes
#SBATCH --ntasks=2
#SBATCH --nodes=2
#SBATCH --gres="gpu:full:8"
#SBATCH --mem="400000mb"
#SBATCH --partition=advanced
#SBATCH --time=12:00:00

source /home/abc/anaconda3/etc/profile.d/conda.sh
conda activate llama_recipes
export PYTHONPATH=$PYTHONPATH:/home/abc/llama_recipes/

nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)
# Enable for A100
export FI_PROVIDER="efa"

echo Node IP: $head_node_ip
export LOGLEVEL=INFO
# debugging flags (optional)
export NCCL_DEBUG=INFO
export NCCL_DEBUG_SUBSYS=INFO
export PYTHONFAULTHANDLER=1
#export LD_LIBRARY_PATH=/opt/amazon/efa/lib:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
export CUDA_LAUNCH_BLOCKING=0


# on your cluster you might need these:
# set the network interface
#export NCCL_SOCKET_IFNAME="eno1"
#export FI_EFA_USE_DEVICE_RDMA=1

srun torchrun --nproc_per_node 8 --nnodes 2  --rdzv_id $RANDOM --rdzv_backend c10d --rdzv_endpoint $head_node_ip:29500 examples/finetuning.py  --enable_fsdp --use_peft --peft_method lora --low_cpu_fsdp

If I start my code with 
srun torchrun --nproc_per_node 8 --nnodes 2 ...,
after submitting my slurm script, I'm not able to call srun --jobid <id> nvidia-smi to check my GPU memory utilization. But the training works perfectly.
If I start my code without srun, only with
torchrun --nproc_per_node 8 --nnodes 2 ...,
I can check GPU memory utilization with srun --jobid <id> nvidia-smi. However the training doesn't work and get torch.distributed.elastic.rendezvous.api.RendezvousTimeoutError
Best regards

**Comment by jens5588** [comment]
@HamidShojanazeri, hi, I have another question regarding the torch run parameter --nnodes and batch_size_training. I have set batch_size_training=1. And I observed as I increased the numbers of --nnodes (from 1 to 2), the training steps in each epoch reduced.  It seems that it's doing parallel training in the sense of data and leads to the OOM error, although I set the batch_size_training=1. This is not what I want. How can I avoid parallel training with FSDP? How does FSDP take care of copies of different machines? Can we force FSDP to distribute all layers to two machines with only one copy?
Best regards

**Comment by jens5588** [comment]
@HamidShojanazeri Thanks a lot for the explanations. I have managed to train the model with reduced context length (around 3000) with 16 A100-40GB GPUs. I still have a question regarding inference. We're doing inference with the transformers library with the fine-tuned model. I have heard FSDP is not suitable for inference (generation). Do you have any idea which framework works compatible with the transformers for multi-node generation?

**Comment by jens5588** [comment]
> @HamidShojanazeri it works, and thanks for your quick response. And I have another issue regarding SLURM. In the following, I show my adapted SLURM script based on multi_node.slurm #!/bin/bash #SBATCH --job-name=llama_recipes #SBATCH --ntasks=2 #SBATCH --nodes=2 #SBATCH --gres="gpu:full:8" #SBATCH --mem="400000mb" #SBATCH --partition=advanced #SBATCH --time=12:00:00
> 
> source /home/abc/anaconda3/etc/profile.d/conda.sh conda activate llama_recipes export PYTHONPATH=$PYTHONPATH:/home/abc/llama_recipes/
> 
> nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) ) nodes_array=($nodes) head_node=${nodes_array[0]} head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)
> 
> export FI_PROVIDER="efa"
> 
> echo Node IP: $head_node_ip export LOGLEVEL=INFO
> 
> export NCCL_DEBUG=INFO export NCCL_DEBUG_SUBSYS=INFO export PYTHONFAULTHANDLER=1
> 
> export CUDA_LAUNCH_BLOCKING=0
> 
> srun torchrun --nproc_per_node 8 --nnodes 2 --rdzv_id $RANDOM --rdzv_backend c10d --rdzv_endpoint $head_node_ip:29500 examples/finetuning.py --enable_fsdp --use_peft --peft_method lora --low_cpu_fsdp
> 
> If I start my code with srun torchrun --nproc_per_node 8 --nnodes 2 ..., after submitting my slurm script, I'm not able to call srun --jobid nvidia-smi to check my GPU memory utilization. But the training works perfectly. If I start my code without srun, only with torchrun --nproc_per_node 8 --nnodes 2 ..., I can check GPU memory utilization with srun --jobid nvidia-smi. However, the training doesn't work and gets a torch.distributed.elastic.rendezvous.api.RendezvousTimeoutError Best regards

Our system administrator has found a solution for the problem. It works with srun --overlap --jobid <jobid> nvidia-smi

**Comment by HamidShojanazeri** [comment]
> @HamidShojanazeri Thanks a lot for the explanations. I have managed to train the model with reduced context length (around 3000) with 16 A100-40GB GPUs. I still have a question regarding inference. We're doing inference with the transformers library with the fine-tuned model. I have heard FSDP is not suitable for inference (generation). Do you have any idea which framework works compatible with the transformers for multi-node generation?

Thats rights, as it has the all reduce in every forward call that is not optimum for inference. I wonder if you like to give [vllm](https://github.com/facebookresearch/llama-recipes/tree/main/examples/vllm) or [TGI](https://github.com/facebookresearch/llama-recipes/tree/main/examples/hf_text_generation_inference) a try for multi-gpu inference.

**Comment by HamidShojanazeri** [comment]
@jens5588 Thanks for the updates, I will close this issue but pls feel free to re-open if have more questions.

**Comment by deema-A** [comment]
> @HamidShojanazeri it works, and thanks for your quick response. And I have another issue regarding SLURM. In the following, I show my adapted SLURM script based on multi_node.slurm #!/bin/bash #SBATCH --job-name=llama_recipes #SBATCH --ntasks=2 #SBATCH --nodes=2 #SBATCH --gres="gpu:full:8" #SBATCH --mem="400000mb" #SBATCH --partition=advanced #SBATCH --time=12:00:00
> 
> source /home/abc/anaconda3/etc/profile.d/conda.sh conda activate llama_recipes export PYTHONPATH=$PYTHONPATH:/home/abc/llama_recipes/
> 
> nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) ) nodes_array=($nodes) head_node=${nodes_array[0]} head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)
> 
> export FI_PROVIDER="efa"
> 
> echo Node IP: $head_node_ip export LOGLEVEL=INFO
> 
> export NCCL_DEBUG=INFO export NCCL_DEBUG_SUBSYS=INFO export PYTHONFAULTHANDLER=1
> 
> export CUDA_LAUNCH_BLOCKING=0
> 
> srun torchrun --nproc_per_node 8 --nnodes 2 --rdzv_id $RANDOM --rdzv_backend c10d --rdzv_endpoint $head_node_ip:29500 examples/finetuning.py --enable_fsdp --use_peft --peft_method lora --low_cpu_fsdp
> 
> If I start my code with srun torchrun --nproc_per_node 8 --nnodes 2 ..., after submitting my slurm script, I'm not able to call srun --jobid nvidia-smi to check my GPU memory utilization. But the training works perfectly. If I start my code without srun, only with torchrun --nproc_per_node 8 --nnodes 2 ..., I can check GPU memory utilization with srun --jobid nvidia-smi. However, the training doesn't work and gets a torch.distributed.elastic.rendezvous.api.RendezvousTimeoutError Best regards

Thank you for sharing this script. I'm curious about how to adapt it for tensor-parallel settings. I have four nodes, each with two GPUs, and I would like to perform inference with the Llama 70B model. I'm not interested in data parallelization. Do you have any suggestions?

thanks!
