### ISSUE TITLE
Windows+jupyternotebook运行llama-recipes报错bitsandbytes

### ISSUE THREAD

**Issue by liujie316316** [facebookresearch/llama-recipes#358]
### System Info

![image](https://github.com/facebookresearch/llama-recipes/assets/44899079/a64644bb-ec93-453f-86a1-7026b13d8874)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

![image](https://github.com/facebookresearch/llama-recipes/assets/44899079/d1541b89-fdd5-427f-9e68-5837d3fb7e5b)

### Error logs

![image](https://github.com/facebookresearch/llama-recipes/assets/44899079/102e9201-8e51-4c65-8e90-1c118f3d7003)
![image](https://github.com/facebookresearch/llama-recipes/assets/44899079/d5a7c323-a634-41ed-99c4-86c16243380d)

### Expected behavior

当我执行下面语句时报错import torch
from transformers import LlamaForCausalLM, LlamaTokenizer

model_id="模型路径"

tokenizer = LlamaTokenizer.from_pretrained(model_id)

model =LlamaForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)

**Comment by HamidShojanazeri** [comment]
@liujie316316 sorry it seems bit&bytes doesn;t support windows, you may want to git rid of "load_in_8bit=True" or "--quantization" in llama-recipe.
