### ISSUE TITLE
Token limit error while inferencing finetuned llama 2 7b chat model

### ISSUE THREAD

**Issue by VrushaliJoshi-v37040** [facebookresearch/llama-recipes#368]
I have fine tuned a llama2 7b chat model on custom dataset. While inferencing the model I am providing text as context and question in the prompt to the model. 
I have checked that the number of tokens in the prompt + max new tokens are not exceeding 4096 still I am getting the following error.

An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (422) from primary with message "{"error":"Input validation error: `inputs` tokens + `max_new_tokens` must be <= 4096. Given: 8509 `inputs` tokens and 64 `max_new_tokens`","error_type":"validation"

Are there any additional tokens that get added while text generation that I am missing out which should be considered while keeping the token limit for the prompt in mind?

**Comment by HamidShojanazeri** [comment]
@VrushaliJoshi-v37040 can you pls point me how you are doing the inference?

**Comment by VrushaliJoshi-v37040** [comment]
> @VrushaliJoshi-v37040 can you pls point me how you are doing the inference?

Hey I figured out the issue. Internally the model tokenizer generates more number of tokens which is different from what we get from a normal word level tokenizer.
