### ISSUE TITLE
Possible bug: error while using quantization

### ISSUE THREAD

**Issue by vivekmadan2** [facebookresearch/llama-recipes#38]
While fine-tuning for 13B with PEFT (LORA) and quantized model, run into the following error:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:6!
utis/train_utils.py    total_loss += loss.detach().float()

First step is completed. Error occurs in the second step. 

Command: 
python3 llama_finetuning.py --use_peft --peft_method lora --model_name /PATH/TO/13B --pure_bf16 --dist_checkpoint_root_folder model_checkpoints --dist_checkpoint_folder fine-tuned --batch_size_training 1 --micro_batch_size 1 --quantization

**Comment by HamidShojanazeri** [comment]
@vivekmadan2 in case you are using single GPU training, please make sure to mask other gpus https://github.com/facebookresearch/llama-recipes/blob/main/README.md#single-gpu,

In this case you would only need output_dir

```
python llama_finetuning.py  --use_peft --peft_method lora --quantization --model_name /patht_of_model_folder/7B --output_dir Path/to/save/PEFT/model

```

In case you are intending to use FSDP + LORA, please note quantization `int8` does not work with FSDP at the moment. 
 and make sure to pass `enable_fsdp`, and again only `outpur_dir` is needed to save PEFT modules.

```
torchrun --nnodes 1 --nproc_per_node 4  llama_finetuning.py --enable_fsdp --use_peft --peft_method lora --model_name /patht_of_model_folder/7B --pure_bf16 --output_dir Path/to/save/PEFT/model
```

**Comment by HamidShojanazeri** [comment]
This PR also should address the issue in general without masking your other gpus. https://github.com/facebookresearch/llama-recipes/pull/40
