### ISSUE TITLE
Input length parameter not working appropriately

### ISSUE THREAD

**Issue by vivekmadan2** [facebookresearch/llama-recipes#42]
Even when specifying input length  256, when we run finetuning, input to the model is 2048. This is because chunk size is defined to be 2048 https://github.com/facebookresearch/llama-recipes/blob/main/ft_datasets/utils.py

**Comment by HamidShojanazeri** [comment]
Thanks @vivekmadan2  for brining this to our attention, to unblock you just please change the context size value in the script you linked up above, will have a PR soon.

**Comment by vivekmadan2** [comment]
Thanks @HamidShojanazeri ! I did make the change and it worked.
