### ISSUE TITLE
ERROR occurred when ‘from transformers import LlamaForCausalLM, LlamaTokenizer’

### ISSUE THREAD

**Issue by xxSpencer** [facebookresearch/llama-recipes#46]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA version lower than 11 are currently not supported for LLM.int8(). You will be only to use 8-bit optimizers and quantization routines!!
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 102
CUDA SETUP: Required library version not found: libbitsandbytes_cuda102.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=102
python setup.py install
CUDA SETUP: Setup Failed!
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File /opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py:1099, in _LazyModule._get_module(self, module_name)
   1098 try:
-> 1099     return importlib.import_module("." + module_name, self.__name__)
   1100 except Exception as e:

File /opt/conda/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1050, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1006, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:688, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:883, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File /opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:32, in <module>
     31 from ...modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast, SequenceClassifierOutputWithPast
---> 32 from ...modeling_utils import PreTrainedModel
     33 from ...utils import add_start_docstrings, add_start_docstrings_to_model_forward, logging, replace_return_docstrings

File /opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py:86, in <module>
     85 if is_accelerate_available():
---> 86     from accelerate import dispatch_model, infer_auto_device_map, init_empty_weights
     87     from accelerate.utils import (
     88         check_tied_parameters_on_same_device,
     89         find_tied_parameters,
   (...)
     94         set_module_tensor_to_device,
     95     )

File /opt/conda/lib/python3.10/site-packages/accelerate/__init__.py:3, in <module>
      1 __version__ = "0.21.0"
----> 3 from .accelerator import Accelerator
      4 from .big_modeling import (
      5     cpu_offload,
      6     cpu_offload_with_hook,
   (...)
     11     load_checkpoint_and_dispatch,
     12 )

File /opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py:35, in <module>
     33 import torch.utils.hooks as hooks
---> 35 from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
     36 from .data_loader import DataLoaderDispatcher, prepare_data_loader, skip_first_batches

File /opt/conda/lib/python3.10/site-packages/accelerate/checkpointing.py:24, in <module>
     22 from torch.cuda.amp import GradScaler
---> 24 from .utils import (
     25     MODEL_NAME,
     26     OPTIMIZER_NAME,
     27     RNG_STATE_NAME,
     28     SCALER_NAME,
     29     SCHEDULER_NAME,
     30     get_pretty_name,
     31     is_tpu_available,
     32     is_xpu_available,
     33     save,
     34 )
     37 if is_tpu_available(check_device=False):

File /opt/conda/lib/python3.10/site-packages/accelerate/utils/__init__.py:131, in <module>
    122     from .deepspeed import (
    123         DeepSpeedEngineWrapper,
    124         DeepSpeedOptimizerWrapper,
   (...)
    128         HfDeepSpeedConfig,
    129     )
--> 131 from .bnb import has_4bit_bnb_layers, load_and_quantize_model
    132 from .fsdp_utils import load_fsdp_model, load_fsdp_optimizer, save_fsdp_model, save_fsdp_optimizer

File /opt/conda/lib/python3.10/site-packages/accelerate/utils/bnb.py:42, in <module>
     41 if is_bnb_available():
---> 42     import bitsandbytes as bnb
     44 from copy import deepcopy

File /opt/conda/lib/python3.10/site-packages/bitsandbytes/__init__.py:6, in <module>
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from . import cuda_setup, utils, research
      7 from .autograd._functions import (
      8     MatmulLtState,
      9     bmm_cublas,
   (...)
     13     matmul_4bit
     14 )

File /opt/conda/lib/python3.10/site-packages/bitsandbytes/research/__init__.py:1, in <module>
----> 1 from . import nn
      2 from .autograd._functions import (
      3     switchback_bnb,
      4     matmul_fp8_global,
      5     matmul_fp8_mixed,
      6 )

File /opt/conda/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py:1, in <module>
----> 1 from .modules import LinearFP8Mixed, LinearFP8Global

File /opt/conda/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py:8, in <module>
      7 import bitsandbytes as bnb
----> 8 from bitsandbytes.optim import GlobalOptimManager
      9 from bitsandbytes.utils import OutlierTracer, find_outlier_dims

File /opt/conda/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py:6, in <module>
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from bitsandbytes.cextension import COMPILED_WITH_CUDA
      8 from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit

File /opt/conda/lib/python3.10/site-packages/bitsandbytes/cextension.py:20, in <module>
     19     CUDASetup.get_instance().print_log_stack()
---> 20     raise RuntimeError('''
     21     CUDA Setup failed despite GPU being available. Please run the following command to get more information:
     22 
     23     python -m bitsandbytes
     24 
     25     Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
     26     to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
     27     and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues''')
     28 lib.cadam32bit_grad_fp32 # runs on an error if the library could not be found -> COMPILED_WITH_CUDA=False

RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Input In [13], in <cell line: 2>()
      1 import torch
----> 2 from transformers import LlamaForCausalLM, LlamaTokenizer

File <frozen importlib._bootstrap>:1075, in _handle_fromlist(module, fromlist, import_, recursive)

File /opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py:1090, in _LazyModule.__getattr__(self, name)
   1088 elif name in self._class_to_module.keys():
   1089     module = self._get_module(self._class_to_module[name])
-> 1090     value = getattr(module, name)
   1091 else:
   1092     raise AttributeError(f"module {self.__name__} has no attribute {name}")

File /opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py:1089, in _LazyModule.__getattr__(self, name)
   1087     value = self._get_module(name)
   1088 elif name in self._class_to_module.keys():
-> 1089     module = self._get_module(self._class_to_module[name])
   1090     value = getattr(module, name)
   1091 else:

File /opt/conda/lib/python3.10/site-packages/transformers/utils/import_utils.py:1101, in _LazyModule._get_module(self, module_name)
   1099     return importlib.import_module("." + module_name, self.__name__)
   1100 except Exception as e:
-> 1101     raise RuntimeError(
   1102         f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1103         f" traceback):\n{e}"
   1104     ) from e

RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by chauhang** [comment]
@xxSpencer Please upgrade to CUDA ver 11.8 or higher. If you continue to face issues with bitsandbytes, then please open issue in their [repo](https://github.com/TimDettmers/bitsandbytes). You can test your install setup of bitsandbytes by running `python -m bitsandbytes`

**Comment by HamidShojanazeri** [comment]
closing this as there is no more updates.
