### ISSUE TITLE
cfg.checkpoint_folder is not defined when using StateDictType.FULL_STATE_DICT

### ISSUE THREAD

**Issue by drcege** [facebookresearch/llama-recipes#48]
When fine-tuning with `StateDictType.FULL_STATE_DICT`, the program crashes when saving checkpoint.

The error is caused here
https://github.com/facebookresearch/llama-recipes/blob/74bde65a62667a38ee0411676cf058c53f85771c/model_checkpointing/checkpoint_handler.py#L145

I know this can be easily solved by assigning `cfg.checkpoint_folder` some value, but just curious why adding another config rather than using `cfg.dist_checkpoint_root_folder` and `cfg.dist_checkpoint_folder`.

Besides, using two `dist_` configs is also strange. Isn't one such config enough?

**Comment by HamidShojanazeri** [comment]
Thanks @drcege for trying it out, it was mostly legacy from previous config format, been fixed in this PR, https://github.com/facebookresearch/llama-recipes/pull/51.

Also will consider the path reformatting into one folder in a future PR.
