### ISSUE TITLE
How to convert finetuned (with FSDP, without LORA) to transformers weights?

### ISSUE THREAD

**Issue by vivekmadan2** [facebookresearch/llama-recipes#53]
Finetuning LLama 13B/7B model with FSDP, but without LORA saves the models in a format different from transformers compatible weights (.bin) and original llama weights (.pth). How should we convert them to the transformers compatible weights?

Saved model:
__0_0.distcp  __1_0.distcp  __2_0.distcp  __3_0.distcp  __4_0.distcp  __5_0.distcp  __6_0.distcp  __7_0.distcp

**Comment by HamidShojanazeri** [comment]
@vivekmadan2 yes, that how FSDP Sharded_Stated_dict checkpoints are you can use the converter script in this[ PR](https://github.com/facebookresearch/llama-recipes/pull/39) is want to convert it back to HF formats, we will merge this soon.
