### ISSUE TITLE
device_map being controlled by wrong flag

### ISSUE THREAD

**Issue by aditya-essential** [facebookresearch/llama-recipes#54]
Shouldn't the device_map https://github.com/facebookresearch/llama-recipes/blob/main/llama_finetuning.py#L96

be controlled by https://github.com/facebookresearch/llama-recipes/blob/main/configs/training.py#L30 instead?

**Comment by HamidShojanazeri** [comment]
@aditya-essential that can be done as well, generally using quantization/ load_in_8bits we need to make device set to `auto`, also given quantization wont work with FSDP at the moment so anything beyond 1 GPU in this context wont work with that, so it means basically one_gpu as well.
