### ISSUE TITLE
How to perform inference by loading Fine-tuned Models using FSDP-only optimization?

### ISSUE THREAD

**Issue by XCD4P** [facebookresearch/llama-recipes#58]
<img width="843" alt="image" src="https://github.com/facebookresearch/llama-recipes/assets/47018977/ab9bc06b-ea27-4f4d-b7e8-7f40bb91d652">
When I finish fine-tuning, I try to perform inference by running the following command:
cat ./inference/alpaca_prompt.txt | python ./inference/inference.py --model_name ./FSDP/fsdp-fine-tuned-./models_hf/7B
However, I encounter an error stating "OSError: ./FSDP/fine-tuned-./models_hf/7B does not appear to have a file named config.json."

I need assistance in resolving this issue and successfully running the inference. Could you please help me with it?

**Comment by HamidShojanazeri** [comment]
@XCD4P can you pls make use of this [PR](https://github.com/facebookresearch/llama-recipes/pull/39), here you would need to do the following

1- convert FSDP checkpoints to HF checkpoints using the converter script

```
 python checkpoint_converter_fsdp_hf.py --fsdp_checkpoint_path  PATH/to/FSDP/Checkpoints --consolidated_model_path PATH/to/save/checkpoints --HF_model_path PATH/or/HF/model_name
 ```
 2- run the inference script as you are already doing, this time it with the checkpoints converted to HF.

**Comment by XCD4P** [comment]
thanks a lot
