### ISSUE TITLE
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

### ISSUE THREAD

**Issue by kushalj001** [facebookresearch/llama-recipes#59]
The code takes some environment variables in `llama_finetuning.py`. Is there a reference as to how should I set them?

**Comment by HamidShojanazeri** [comment]
@kushalj001 if you running with torchrun, https://github.com/facebookresearch/llama-recipes/tree/main#multiple-gpus-one-node they would be set automatically, also part of the debug flags are being set again automatically calling this func in the script, https://github.com/facebookresearch/llama-recipes/blob/main/utils/train_utils.py#L248
