### ISSUE TITLE
Installable (PyPi) version of the library?

### ISSUE THREAD

**Issue by vivekmadan2** [facebookresearch/llama-recipes#60]
Is there a plan to make this a PyPi library?

Meanwhile, can we get similar utility? In particular, if I want to fine-tune it on a custom dataset but do not want to change the code of the repo itself, can I achieve this?

**Comment by HamidShojanazeri** [comment]
@vivekmadan2 , packaging this repo is in discussion and to be decided, but to add custom datasets, you can follow this guide here. https://github.com/facebookresearch/llama-recipes/blob/main/docs/Dataset.md#adding-custom-datasets

**Comment by chauhang** [comment]
@vivekmadan2 The PR https://github.com/facebookresearch/llama-recipes/pull/153 addresses this
