### ISSUE TITLE
How many epochs needed for good results while finetuning?

### ISSUE THREAD

**Issue by kushalj001** [facebookresearch/llama-recipes#61]
Hi,
I finetuned the 7B model with LoRA + 8b quantization on a task (GSM8k) for 4 epochs. But the finetuned weights did not seem to be performing well on the task. I wanted to know if there are any guidelines on the duration/number of epochs that I need to finetune the model for. Also, is there a chance that PEFT tricks are leading to the performance hit?
Thanks

**Comment by HamidShojanazeri** [comment]
It is hard to comment on that, it will depend to your datasets, batch size, setting for LORA, lr  and other factors, but generally suggest to train for longer epochs, on some other datasets I have seen improved results between 8-16 epochs. This might be helpful to check [PEFT examples for int8 training](https://github.com/huggingface/peft/tree/main/examples/int8_training), along with papers that report similar experiments (LORA) for GSM8k, [LORA paper](https://arxiv.org/pdf/2106.09685.pdf) might be helpful as well.
