### ISSUE TITLE
Facing shape mismatch issue with text-classification finetuning

### ISSUE THREAD

**Issue by nvijayrania** [facebookresearch/llama-recipes#66]
I'm using a text-classification dataset [dair-ai/emotion](https://huggingface.co/datasets/dair-ai/emotion)  with LLaMA 7b with FSDP + PEFT and the training fails with the following shape mismatch error.

Below is the implementation of the get_dataset method
```
def get_dataset(dataset_config, tokenizer, split):
    dataset = datasets.load_dataset("dair-ai/emotion", split=split)
    dataset = dataset.map(
        lambda sample: tokenizer(sample["text"], truncation=True, padding="max_length", max_length=dataset_config.max_input_length),
        batched=True,
        remove_columns=["text"],
    )
    return dataset
```

 _File "/anaconda/envs/llama-FT/lib/python3.8/site-packages/torch/nn/functional.py", line 3055, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
ValueError: Expected input batch_size (2044) to match target batch_size (3)._

I'm using pytorch-nightly and using samsum dataset, the finetuing with FSDP + PEFT is working.
For classification dataset, do we need to change something in FSDP wrapper as well?

**Comment by HamidShojanazeri** [comment]
@nvijayrania so you mean you have added the dair-ai/emotion dataset following the this doc, https://github.com/facebookresearch/llama-recipes/blob/main/docs/Dataset.md#adding-custom-datasets and now its failing?

**Comment by HamidShojanazeri** [comment]
@nvijayrania I was wondering if you have followed this doc to add the new dataset? https://github.com/facebookresearch/llama-recipes/blob/main/docs/Dataset.md#adding-custom-datasets

**Comment by nvijayrania** [comment]
Yes @HamidShojanazeri, I have followed the same doc.

**Comment by nvijayrania** [comment]
My bad, I should use `LlamaForSequenceClassification` instead of `LlamaForCausalLM`.

**Comment by AmirLayegh** [comment]
@nvijayrania have you been able to fine-tune the model on text classification dataset?

**Comment by nvijayrania** [comment]
yes, I was. TO make it work, I had to add a new dataset as mentioned here https://github.com/facebookresearch/llama-recipes/blob/main/docs/Dataset.md#adding-custom-datasets (snippet added above) and use LlamaForSequenceClassification as model before wrapping it into FSDP.

**Comment by AmirLayegh** [comment]
Thanks for your reply @nvijayrania. I'm trying to fine-tune it on the TACRED dataset. The dataset contains a column of text (which is a sentence) and two columns indicating the subject and object entities in the sentence. the label indicates the relation between these two entities in the sentence. My question is to add the new dataset, should I concatenate the input sentence with the object and subject entities and make them as one column?
sample of the dataset: {sentence: Steve Jobs was co-founder of Apple, subject: Apple, object: Steve Jobs, label: org:founded_by}.

**Comment by AmirLayegh** [comment]
@nvijayrania Thanks for your reply. could you please mention how did you use your tuned model at inference since the `LlamaForSequenceClassification` does not support `model.generate`. Thanks in advance.
