### ISSUE TITLE
In alpaca instruction dataset why are we adding zero pad tokens? also -1 in labels instead of -100.

### ISSUE THREAD

**Issue by monksgoyal** [facebookresearch/llama-recipes#73]
As fas as i understand since llama does not have pad token so we might be adding zero but why are we calculating loss through these tokens as huggingface mentions that -100 should be passed if you dont have to calculate loss. also before prompt we are passing -1 instead of 100 so does that mean loss will algo go through it.

**Comment by HamidShojanazeri** [comment]
addressed in this[ PR](https://github.com/facebookresearch/llama-recipes/pull/107).
