### ISSUE TITLE
How to run multi-gpu inference?

### ISSUE THREAD

**Issue by wang-sj16** [facebookresearch/llama-recipes#76]
### 🚀 The feature, motivation and pitch

Is there a method to run multi-gpu inference? Current inference scripts will get a CUDA error when running with multiple gpus according to my runs and other issues. If not, is it possible to transfer the peft llama ckpt to meta's format to use meta's original scripts to run multi-gpu inference?

**Comment by HamidShojanazeri** [comment]
@wang-sj16 cna you pls elaborate how did you fine-tune, if you did with peft then inference script should be directly usable. In case you had fine-tuned with FSDP only, [this](https://github.com/facebookresearch/llama-recipes/blob/main/docs/inference.md#loading-back-fsdp-checkpoints) should be helpful to convert your FSDP checkpoints to HF checkpoints and use the inference script normally. [Loading model in the inference script](https://github.com/facebookresearch/llama-recipes/blob/main/inference/model_utils.py#L8), make use of HF accelerate that help you to run the model on multi-gpus.

**Comment by wang-sj16** [comment]
Hi, @HamidShojanazeri I fine-tune with PEFT (lora) without FSDP. When eval with multiple gpus with the given inference script, I met the same error with https://github.com/facebookresearch/llama-recipes/issues/64

**Comment by HamidShojanazeri** [comment]
@wang-sj16 can you pls share the command you are running/ model size?

**Comment by jshin49** [comment]
Do we need to use HF Accelerate to run multi-gpu inference using `inference.py`?

**Comment by HamidShojanazeri** [comment]
> Do we need to use HF Accelerate to run multi-gpu inference using `inference.py`?

yes.

**Comment by HamidShojanazeri** [comment]
closing this one as there has been no updates in a while.
