### ISSUE TITLE
The Size of the finetuned model is the same as the converted model

### ISSUE THREAD

**Issue by larawehbe** [facebookresearch/llama-recipes#81]
### System Info

Torch and Transformer dowloaded from this repository so they are aligned with the needed versions
CUDA avilable 
RTX6000 GPU x1  25GB

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

The size of the converted 7B llama2 model is 13G and its the same as the finetuned model. Isn't it weird ? 

### Error logs

They are both of the same size 

### Expected behavior

to have the finetuned model at least slightly greater

**Comment by HamidShojanazeri** [comment]
They are expected to be the same size, the chat model only has been fine-tuned on more data and some other tweaks, please refer to [llama2 paper.](https://arxiv.org/pdf/2307.09288.pdf)

**Comment by larawehbe** [comment]
@HamidShojanazeri So even if i finetune the model on thousands of data entries, it will still be the same size as the main model ? Just for clarification as i didnt know this before.
Thanks!
