### ISSUE TITLE
`load_model_sharded` needs minor fix

### ISSUE THREAD

**Issue by lchu-ibm** [facebookresearch/llama-recipes#87]
### 🐛 Describe the bug

`load_model_sharded` has a minor and needs a quick fix like: https://github.com/facebookresearch/llama-recipes/commit/11341082ababd8981c03dd4d16be780e4b91969f.

I assume this is expected to be used to pair with `save_model_and_optimizer_sharded`, so we need to match the dict key.

cc @HamidShojanazeri

**Comment by HamidShojanazeri** [comment]
@lchu-ibm thanks, can you pls add it to the other PR.
