### ISSUE TITLE
Tensor/pipeline parallelism

### ISSUE THREAD

**Issue by ToddMorrill** [facebookresearch/llama-recipes#89]
### 🚀 The feature, motivation and pitch

First, thanks for this gem of a repo. I'm hoping to continue training at least the 7 and 13b parameter models and trust that FSDP should be up to the task. Have you implemented or do you plan to implement tensor parallelism or pipeline parallelism for training? I might be reading into this but it looks like there's a vestige of 2d parallelism in your Slurm script with the name `Nano-2d-trainer-20b-8nodes`.

**Comment by HamidShojanazeri** [comment]
@ToddMorrill , thanks for your interest in this work. We are not using TP+pipeline in this work and mostly relying on FSDP as the most cost efficient/ user friendly training paradigm for now. For model sizes up to 25B FSDP scale almost linearly, beyond that we might need to add TP as well. We are working on this recipe for 70B. Will fix the name on the slurm script as well.

**Comment by ToddMorrill** [comment]
Are there any examples that attempt to implement tensor parallelism with FSDP? Should I take a closer look at anything in fairscale? For example, I see these parallel objects in the the llama model definition: https://github.com/facebookresearch/llama/blob/6c7fe276574e78057f917549435a2554000a876d/llama/model.py#L11-L15

**Comment by HamidShojanazeri** [comment]
@ToddMorrill you can take a look at this [example](https://github.com/HamidShojanazeri/examples/blob/2d-t5/distributed/FSDP/T5_training.py#L201) that does 2D (TP+FSDP) for T5 model.

**Comment by ToddMorrill** [comment]
Thank you, I will add it to my queue!
