### ISSUE TITLE
Min hardware requirement for 70B

### ISSUE THREAD

**Issue by dittops** [facebookresearch/llama-recipes#96]
What is the hardware requirement (GPU and CPU) for running 70B SFT without peft?

**Comment by HamidShojanazeri** [comment]
@dittops please take a look this [PR for low CPU usage](https://github.com/facebookresearch/llama-recipes/pull/77), This has been tested on 2 nodes 8xA100 80 GB for FSDP only in case interested in PEFT + FSDP this should be more affordable with smaller settings as well.
